var paleocodestore = [{
	"Sign": "𒀀",
	"Code point": "U+12000",
	"Transliteration": "A",
	"Borger": "839",
	"PaleoCode": "a-a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒀁",
	"Code point": "U+12001",
	"Transliteration": "A x A",
	"Borger": "845",
	"PaleoCode": "a-:sa-:sa:sa-a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "EDURU",
	"Source": "",
	"Epoch": "",
	"Meaning": "",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒀂",
	"Code point": "U+12002",
	"Transliteration": "A x BAD",
	"Borger": "840",
	"PaleoCode": "a-b-w-a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "AGAM",
	"Source": "",
	"Epoch": "",
	"Meaning": "artificial pond",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒋰",
	"Code point": "U+122F0",
	"Transliteration": "TAB",
	"Borger": "209",
	"PaleoCode": "b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒌑",
	"Code point": "U+12311",
	"Transliteration": "U2",
	"Borger": "490",
	"PaleoCode": "B::B-a-a-a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒀾",
	"Code point": "U+1203E",
	"Transliteration": "ASZ2",
	"Borger": "548",
	"PaleoCode": "b:b:b:b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": ["wish","curse"],
	"Concept":"https://www.wikidata.org/wiki/Q241625",
	"Location": ""
}, {
	"Sign": "𒇲",
	"Code point": "U+121F2",
	"Transliteration": "LAL",
	"Borger": "750",
	"PaleoCode": "a-b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒁇",
	"Code point": "U+12047",
	"Transliteration": "BAR",
	"Borger": "121",
	"PaleoCode": ";b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒂃",
	"Code point": "U+12083",
	"Transliteration": "DUH",
	"Borger": "298",
	"PaleoCode": "/b:b_w:w-w:w-w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "GAB, DU8, TUH",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂉",
	"Code point": "U+12089",
	"Transliteration": "DUR2",
	"Borger": "808",
	"PaleoCode": "a-b;b-::b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "DURU2, DURUN, TUKUL, TUSZ",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃲",
	"Code point": "U+120F2",
	"Transliteration": "GAL",
	"Borger": "553",
	"PaleoCode": "b:b:b:b_a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇹",
	"Code point": "U+121F9",
	"Transliteration": "LIMMU2",
	"Borger": "215",
	"PaleoCode": "b:b_b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄩",
	"Code point": "U+12129",
	"Transliteration": "HA",
	"Borger": "856",
	"PaleoCode": "a:a;w-a:a-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "KU6",
	"Source": "",
	"Epoch": ""
}, {
	"Sign": "𒆳",
	"Code point": "U+121B3",
	"Transliteration": "KUR",
	"Borger": "578",
	"PaleoCode": "w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈦",
	"Code point": "U+12226",
	"Transliteration": "MASZ",
	"Borger": "120",
	"PaleoCode": ":b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": ""
}, {
	"Sign": "𒆜",
	"Code point": "U+1219C",
	"Transliteration": "KASKAL",
	"Borger": "302",
	"PaleoCode": "::c'd-::d'c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆕",
	"Code point": "U+12195",
	"Transliteration": "KAK",
	"Borger": "379",
	"PaleoCode": "a:<C:>D",
	"SVG": "",
	"Gottstein": "",
	"Comment": "GAG, DU3, RU2",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆚",
	"Code point": "U+1219A",
	"Transliteration": "KAM2",
	"Borger": "595",
	"PaleoCode": "c:c-c:c:c-c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈛",
	"Code point": "U+1221B",
	"Transliteration": "LUH",
	"Borger": "494",
	"PaleoCode": "b:b:b:b_a-a-a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈠",
	"Code point": "U+12220",
	"Transliteration": "MA",
	"Borger": "552",
	"PaleoCode": "b_a;b-:b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉡",
	"Code point": "U+12261",
	"Transliteration": "NU",
	"Borger": "112",
	"PaleoCode": ":B-A;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀫",
	"Code point": "U+1202B",
	"Transliteration": "AMAR",
	"Borger": "695",
	"PaleoCode": "w:w_/b:b_w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃵",
	"Code point": "U+120F5",
	"Transliteration": "GAM",
	"Borger": "576",
	"PaleoCode": "c.c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊸",
	"Code point": "U+122B8",
	"Transliteration": "SZAB6",
	"Borger": "",
	"PaleoCode": "/b:b_b:b:b_:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄑",
	"Code point": "U+12111",
	"Transliteration": "GISZ",
	"Borger": "469",
	"PaleoCode": "b::b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄨",
	"Code point": "U+12128",
	"Transliteration": "GURUSZ",
	"Borger": "",
	"PaleoCode": "b:::b-a--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄷",
	"Code point": "U+12137",
	"Transliteration": "HU",
	"Borger": "132",
	"PaleoCode": ":b-a-::w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄿",
	"Code point": "U+1213F",
	"Transliteration": "I",
	"Borger": "252",
	"PaleoCode": "b:b:b_/b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈨",
	"Code point": "U+12228",
	"Transliteration": "ME",
	"Borger": "753",
	"PaleoCode": "a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈫",
	"Code point": "U+1222B",
	"Transliteration": "MIN",
	"Borger": "825",
	"PaleoCode": "a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋙",
	"Code point": "U+122D9",
	"Transliteration": "SZU2",
	"Borger": "869",
	"PaleoCode": "a;w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌷",
	"Code point": "U+12337",
	"Transliteration": "URU",
	"Borger": "071",
	"PaleoCode": "::b::b-a--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍝",
	"Code point": "U+1235D",
	"Transliteration": "ZA",
	"Borger": "851",
	"PaleoCode": "a::a-a::a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀸",
	"Code point": "U+12038",
	"Transliteration": "ASZ",
	"Borger": "001",
	"PaleoCode": "b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁹",
	"Code point": "U+12079",
	"Transliteration": "DISZ",
	"Borger": "748",
	"PaleoCode": "a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄐",
	"Code point": "U+12110",
	"Transliteration": "GISAL",
	"Borger": "376",
	"PaleoCode": "b;b_ac:::d_b;b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄬",
	"Code point": "U+1212C",
	"Transliteration": "HAL",
	"Borger": "003",
	"PaleoCode": ":/bc:d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": ""
}, {
	"Sign": "𒃻",
	"Code point": "U+120FB",
	"Transliteration": "GAR",
	"Borger": "859",
	"PaleoCode": "a-:sa-sa~~:::f",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅀",
	"Code point": "U+12140",
	"Transliteration": "I A",
	"Borger": "",
	"PaleoCode": "b:b:b_/b:b_a-a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅆",
	"Code point": "U+12146",
	"Transliteration": "IGI",
	"Borger": "724",
	"PaleoCode": ":W-a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅈",
	"Code point": "U+12148",
	"Transliteration": "IGI RI",
	"Borger": "726",
	"PaleoCode": ":w-a-:b_-:b-a-a-:::w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈥",
	"Code point": "U+12225",
	"Transliteration": "MAR",
	"Borger": "483",
	"PaleoCode": "b:::b_a-a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈪",
	"Code point": "U+1222A",
	"Transliteration": "MI",
	"Borger": "681",
	"PaleoCode": "W_b:b:b:b_b:b:b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈬",
	"Code point": "U+1222C",
	"Transliteration": "MU",
	"Borger": "098",
	"PaleoCode": ":B'w::w-w::w--w::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉼",
	"Code point": "U+1227C",
	"Transliteration": "PAN",
	"Borger": "685",
	"PaleoCode": "c_d_c_d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊩",
	"Code point": "U+122A9",
	"Transliteration": "SAL",
	"Borger": "883",
	"PaleoCode": "a::bcb::d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊭",
	"Code point": "U+122AD",
	"Transliteration": "SZA",
	"Borger": "566",
	"PaleoCode": "b:b:b:b_ac:::d_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊺",
	"Code point": "U+122BA",
	"Transliteration": "SZE",
	"Borger": "579",
	"PaleoCode": "W:W-w:w-w:w-w:w-W:W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌀",
	"Code point": "U+12300",
	"Transliteration": "TIL",
	"Borger": "114",
	"PaleoCode": "bc",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈝",
	"Code point": "U+1221D",
	"Transliteration": "LUM",
	"Borger": "900",
	"PaleoCode": "c:c:c_d:d:d_c:c:c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈣",
	"Code point": "U+12223",
	"Transliteration": "MA2",
	"Borger": "201",
	"PaleoCode": "Bsa-;b'::sa_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁄",
	"Code point": "U+12044",
	"Transliteration": "BAL",
	"Borger": "005",
	"PaleoCode": ":b-:b_:W-a-:b--/w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀹",
	"Code point": "U+12039",
	"Transliteration": "ASZ ZIDA tenu",
	"Borger": "575",
	"PaleoCode": "c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀺",
	"Code point": "U+1203A",
	"Transliteration": "ASZ KABA tenu",
	"Borger": "647?",
	"PaleoCode": "e",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀼",
	"Code point": "U+1203C",
	"Transliteration": "ASZ / ASZ / ASZ",
	"Borger": "505",
	"PaleoCode": "b:b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄧",
	"Code point": "U+12127",
	"Transliteration": "GURUN",
	"Borger": "503",
	"PaleoCode": "b:::b_a;w-a;w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆦",
	"Code point": "U+121A6",
	"Transliteration": "KISAL",
	"Borger": "435",
	"PaleoCode": "b:b:b:b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉒",
	"Code point": "U+12252",
	"Transliteration": "NINDA2",
	"Borger": "316",
	"PaleoCode": "::b:b_a-B;B",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉺",
	"Code point": "U+1227A",
	"Transliteration": "PA",
	"Borger": "464",
	"PaleoCode": "b:::b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉽",
	"Code point": "U+1227D",
	"Transliteration": "PAP",
	"Borger": "092",
	"PaleoCode": "c:d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊬",
	"Code point": "U+122AC",
	"Transliteration": "SAR",
	"Borger": "541",
	"PaleoCode": "W:W:W-W:W:W-W:W:W-a-b;b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋂",
	"Code point": "U+122C2",
	"Transliteration": "SZESZLAM",
	"Borger": "100",
	"PaleoCode": "sc:sb--a:a-a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋃",
	"Code point": "U+122C3",
	"Transliteration": "SZID",
	"Borger": "485",
	"PaleoCode": "B:B:B:b-a-a;b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋖",
	"Code point": "U+122D6",
	"Transliteration": "SZITA",
	"Borger": "388",
	"PaleoCode": "A:c;d_A",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋗",
	"Code point": "U+122D7",
	"Transliteration": "SZU",
	"Borger": "567",
	"PaleoCode": "b:b:b:b:b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍞",
	"Code point": "U+1235E",
	"Transliteration": "ZA tenu",
	"Borger": "854",
	"PaleoCode": "c.c-c.c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍭",
	"Code point": "U+1236D",
	"Transliteration": "ZUBUR",
	"Borger": "648",
	"PaleoCode": "e:e:e",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌍",
	"Code point": "U+1230D",
	"Transliteration": "U U U",
	"Borger": "711",
	"PaleoCode": "W-W-W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌋",
	"Code point": "U+1230B",
	"Transliteration": "U",
	"Borger": "661",
	"PaleoCode": "W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋻",
	"Code point": "U+122FB",
	"Transliteration": "TAR",
	"Borger": "009",
	"PaleoCode": "c.ca",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋾",
	"Code point": "U+122FE",
	"Transliteration": "TI",
	"Borger": "118",
	"PaleoCode": ":b_:w-a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀖",
	"Code point": "U+12016",
	"Transliteration": "AB2",
	"Borger": "672",
	"PaleoCode": "W-c;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐀",
	"Code point": "U+12400",
	"Transliteration": "two ASZ",
	"Borger": "002",
	"PaleoCode": "b-b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐁",
	"Code point": "U+12401",
	"Transliteration": "three ASZ",
	"Borger": "004",
	"PaleoCode": "b-b-b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐂",
	"Code point": "U+12402",
	"Transliteration": "four ASZ",
	"Borger": "215",
	"PaleoCode": "b:b_b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐃",
	"Code point": "U+12403",
	"Transliteration": "five ASZ",
	"Borger": "216",
	"PaleoCode": "b:b_b:b_b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐄",
	"Code point": "U+12404",
	"Transliteration": "six ASZ",
	"Borger": "217",
	"PaleoCode": "b:b_b:b_b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐅",
	"Code point": "U+12405",
	"Transliteration": "seven ASZ",
	"Borger": "218",
	"PaleoCode": "b:b_b:b_b:b_b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐆",
	"Code point": "U+12406",
	"Transliteration": "eight ASZ",
	"Borger": "219",
	"PaleoCode": "b:b_b:b_b:b_b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐇",
	"Code point": "U+12407",
	"Transliteration": "nine ASZ",
	"Borger": "220",
	"PaleoCode": "b:b_b:b_b:b_b:b_b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐏",
	"Code point": "U+1240F",
	"Transliteration": "four U",
	"Borger": "713",
	"PaleoCode": "w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐐",
	"Code point": "U+12410",
	"Transliteration": "five U",
	"Borger": "714",
	"PaleoCode": "w:w-w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐑",
	"Code point": "U+12411",
	"Transliteration": "six U",
	"Borger": "715",
	"PaleoCode": "w:w-w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐒",
	"Code point": "U+12412",
	"Transliteration": "seven U",
	"Borger": "716",
	"PaleoCode": "w:w-w:w-w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐓",
	"Code point": "U+12413",
	"Transliteration": "eight U",
	"Borger": "717",
	"PaleoCode": "w:w-w:w-w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐔",
	"Code point": "U+12414",
	"Transliteration": "nine U",
	"Borger": "718",
	"PaleoCode": "w:w-w:w-w:w-w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑁",
	"Code point": "U+12441",
	"Transliteration": "IMIN3",
	"Borger": "537",
	"PaleoCode": "b:b:b_b:b:b_b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑆",
	"Code point": "U+12446",
	"Transliteration": "ILIMMU",
	"Borger": "868",
	"PaleoCode": "a:a:a-a:a:a-a:a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑈",
	"Code point": "U+12448",
	"Transliteration": "ILIMMU4",
	"Borger": "577",
	"PaleoCode": "w.w.w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑃",
	"Code point": "U+12443",
	"Transliteration": "IMIN variant form",
	"Borger": "866",
	"PaleoCode": "a:a-a:a-a:a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑅",
	"Code point": "U+12445",
	"Transliteration": "USSU3",
	"Borger": "538",
	"PaleoCode": "b:b:b_b:b:b_/b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑇",
	"Code point": "U+12447",
	"Transliteration": "ILIMMU3",
	"Borger": "539",
	"PaleoCode": "b:b:b_b:b:b_b:b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐋",
	"Code point": "U+1240B",
	"Transliteration": "six DISZ",
	"Borger": "862",
	"PaleoCode": "a:a-a:a-a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋥",
	"Code point": "U+122E5",
	"Transliteration": "SUD2",
	"Borger": "139",
	"PaleoCode": ":b_a-a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋡",
	"Code point": "U+122E1",
	"Transliteration": "SILA3",
	"Borger": "099",
	"PaleoCode": "c;d_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄞",
	"Code point": "U+1211E",
	"Transliteration": "GUD",
	"Borger": "472",
	"PaleoCode": "b:::b_a:c::d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "potter",
	"Concept": "https://www.wikidata.org/wiki/Q3400050",
	"Location": ""
}, {
	"Sign": "𒃾",
	"Code point": "U+120FE",
	"Transliteration": "GESZTIN",
	"Borger": "212",
	"PaleoCode": "b:::b'::sa-::sa-w:::w-c;d'",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄾",
	"Code point": "U+1213E",
	"Transliteration": "HUL2",
	"Borger": "877",
	"PaleoCode": "a;w_b:b:b:b-b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "joy",
	"Concept": "https://www.wikidata.org/wiki/Q935526",
	"Location": ""
}, {
	"Sign": "𒅕",
	"Code point": "U+12155",
	"Transliteration": "IR",
	"Borger": "437",
	"PaleoCode": "<;C>>D-:;sa-:;sa-:;sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆗",
	"Code point": "U+12197",
	"Transliteration": "KAL",
	"Borger": "496",
	"PaleoCode": "b:::b-a--a::a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆰",
	"Code point": "U+121B0",
	"Transliteration": "KUL",
	"Borger": "117",
	"PaleoCode": "b-w-b-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀝",
	"Code point": "U+1201D",
	"Transliteration": "AK",
	"Borger": "127",
	"PaleoCode": ":W_b:b:b:b--b:b:b:b_a-:bb",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁳",
	"Code point": "U+12073",
	"Transliteration": "DIB",
	"Borger": "813",
	"PaleoCode": ":a-b::sb:sb::b-::sa--:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐻",
	"Code point": "U+1243B",
	"Transliteration": "ESZ21",
	"Borger": "210",
	"PaleoCode": "b:b_b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "three",
	"Concept": "https://www.wikidata.org/wiki/Q201",
	"Location": ""
}, {
	"Sign": "𒑗",
	"Code point": "U+12457",
	"Transliteration": "NIGIDAESZ",
	"Borger": "850",
	"PaleoCode": "a:a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑖",
	"Code point": "U+12456",
	"Transliteration": "NIGIDAMIN",
	"Borger": "847,848",
	"PaleoCode": "a:a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅊",
	"Code point": "U+1214A",
	"Transliteration": "IGI gunu",
	"Borger": "564",
	"PaleoCode": "b:b:b:b':W_a-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "meadow",
	"Concept": "https://www.wikidata.org/wiki/Q7777019",
	"Location": ""
}, {
	"Sign": "𒑙",
	"Code point": "U+12459",
	"Transliteration": "ESZEMIN5 (\"BI\")",
	"Borger": "359",
	"PaleoCode": "b:b_w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆏",
	"Code point": "U+1218F",
	"Transliteration": "KAB",
	"Borger": "148",
	"PaleoCode": "sb:sb:sb:sb:sb:B-a:::sb-:::w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "left hand",
	"Concept": "https://www.wikidata.org/wiki/Q24206676",
	"Location": ""
}, {
	"Sign": "𒆐",
	"Code point": "U+12190",
	"Transliteration": "KAD2",
	"Borger": "108",
	"PaleoCode": ":sbsc-a;w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆑",
	"Code point": "U+12191",
	"Transliteration": "KAD3",
	"Borger": "109",
	"PaleoCode": ":sbsc-a;w-a;w-a;w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃮",
	"Code point": "U+120EE",
	"Transliteration": "GABA",
	"Borger": "",
	"PaleoCode": "b:b_w:w-w:w-w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄓",
	"Code point": "U+12113",
	"Transliteration": "GISZ x BAD",
	"Borger": "471",
	"PaleoCode": "b:sb-sw:b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "an insect",
	"Concept": "https://www.wikidata.org/wiki/Q1390",
	"Location": ""
}, {
	"Sign": "𒁁",
	"Code point": "U+12041",
	"Transliteration": "BAD",
	"Borger": "113",
	"PaleoCode": "/:b_:::sc'sd",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁀",
	"Code point": "U+12040",
	"Transliteration": "BA",
	"Borger": "014",
	"PaleoCode": ">d:::::<<c--/:sb--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁍",
	"Code point": "U+1204D",
	"Transliteration": "BU",
	"Borger": "580",
	"PaleoCode": "cd_cd_b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁎",
	"Code point": "U+1204E",
	"Transliteration": "BU / BU AB",
	"Borger": "582",
	"PaleoCode": "cd;cd_cd;cd_b:::b_:b:b_;::c'd_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁑",
	"Code point": "U+12051",
	"Transliteration": "BULUG",
	"Borger": "169",
	"PaleoCode": "b-a;w-bsc_W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "needle",
	"Concept": "https://www.wikidata.org/wiki/Q142690",
	"Location": ""
}, {
	"Sign": "𒁓",
	"Code point": "U+12053",
	"Transliteration": "BUR",
	"Borger": "559",
	"PaleoCode": "b:b:b:b:b_ac;f",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁔",
	"Code point": "U+12054",
	"Transliteration": "BUR2",
	"Borger": "008",
	"PaleoCode": ":b_ac;d-a_/b--w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁖",
	"Code point": "U+12056",
	"Transliteration": "DAG",
	"Borger": "438",
	"PaleoCode": ";B-ab.ab.ab.ab-;f'c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁮",
	"Code point": "U+1206E",
	"Transliteration": "DAM",
	"Borger": "889",
	"PaleoCode": "a:bcb::d_a-b:::b-::b--a-::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁲",
	"Code point": "U+12072",
	"Transliteration": "DI",
	"Borger": "736",
	"PaleoCode": "f;c_c:b:b::f",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁴",
	"Code point": "U+12074",
	"Transliteration": "DIM",
	"Borger": "167",
	"PaleoCode": ":b_a-a:CD_::cd",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂖",
	"Code point": "U+12096",
	"Transliteration": "EL",
	"Borger": "899",
	"PaleoCode": "a:bcb::d_b-;sb'::sa--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂡",
	"Code point": "U+120A1",
	"Transliteration": "EZEN",
	"Borger": "271",
	"PaleoCode": ":sa-:sb::sb-ab;b_a-:sb::sb-:sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "festival",
	"Concept": "https://www.wikidata.org/wiki/Q132241",
	"Location": ""
}, {
	"Sign": "𒂠",
	"Code point": "U+120A0",
	"Transliteration": "ESZ2",
	"Borger": "810; 811",
	"PaleoCode": "a-b;B-sb:sb:sb:sb:sb_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂷",
	"Code point": "U+120B7",
	"Transliteration": "GA2",
	"Borger": "387",
	"PaleoCode": "b;b';sa-;sa--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃷",
	"Code point": "U+120F7",
	"Transliteration": "GAN2",
	"Borger": "174",
	"PaleoCode": ";B';sa-;sa-b;sa-;sa-;sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉣",
	"Code point": "U+12263",
	"Transliteration": "NUN",
	"Borger": "143",
	"PaleoCode": "::B':sa-:sa-:sa-:sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃰",
	"Code point": "U+120F0",
	"Transliteration": "GAD",
	"Borger": "157",
	"PaleoCode": "d;c_A",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "flax",
	"Concept": "https://www.wikidata.org/wiki/Q47089651",
	"Location": ""
}, {
	"Sign": "𒄥",
	"Code point": "U+12125",
	"Transliteration": "GUR",
	"Borger": "180",
	"PaleoCode": "b:::b-a--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍏",
	"Code point": "U+1234F",
	"Transliteration": "URUDU (URUDA)",
	"Borger": "230",
	"PaleoCode": ":sa-:sb::sb-a-b;b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌝",
	"Code point": "U+1231D",
	"Transliteration": "UM",
	"Borger": "238",
	"PaleoCode": ":sb:sb-a-B;B':sa-:sa-:sa-:sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "disease",
	"Concept": "https://www.wikidata.org/wiki/Q12136",
	"Location": ""
}, {
	"Sign": "𒃴",
	"Code point": "U+120F4",
	"Transliteration": "GALAM (SUKUD)",
	"Borger": "338",
	"PaleoCode": ":sb:sb-a-c;d_/:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉌",
	"Code point": "U+1224C",
	"Transliteration": "NI",
	"Borger": "380",
	"PaleoCode": "c;d-;sa-;sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍑",
	"Code point": "U+12351",
	"Transliteration": "USZ (NITA)",
	"Borger": "381",
	"PaleoCode": "B;b';sa-;sa-:sa-;w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "penis",
	"Concept": "https://www.wikidata.org/wiki/Q58",
	"Location": ""
}, {
	"Sign": "𒆤",
	"Code point": "U+121A4",
	"Transliteration": "KID (LÍL)",
	"Borger": "484",
	"PaleoCode": "b:b:b:b'a-a-a-a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌒",
	"Code point": "U+12312",
	"Transliteration": "UB",
	"Borger": "504",
	"PaleoCode": "d;c_;sa'c;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌙",
	"Code point": "U+12319",
	"Transliteration": "UD-gunu",
	"Borger": "542",
	"PaleoCode": "sb:sb:sb:sb_d;c_a::a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇬",
	"Code point": "U+121EC",
	"Transliteration": "LAGAR",
	"Borger": "719",
	"PaleoCode": "d;c-::sa--A",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆠",
	"Code point": "U+121A0",
	"Transliteration": "KI",
	"Borger": "737",
	"PaleoCode": "f;c_-cb:b:b:b::f",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈨𒌍",
	"Code point": "U+12228 & U+1230D",
	"Transliteration": "MESZ",
	"Borger": "754",
	"PaleoCode": "a-:b_W-W-W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍦",
	"Code point": "U+12366",
	"Transliteration": "ZIB",
	"Borger": "628",
	"PaleoCode": ";sc-':::sc-'::sc-:sc",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍴",
	"Code point": "U+12374",
	"Transliteration": "DAG3",
	"Borger": "",
	"PaleoCode": "b::b-::sa-::sa-:::sc:sc--sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀪",
	"Code point": "U+1202A",
	"Transliteration": "aleph",
	"Borger": "635",
	"PaleoCode": "f;c_-c:b';d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅁",
	"Code point": "U+12141",
	"Transliteration": "IB",
	"Borger": "807",
	"PaleoCode": ";B'a-:B':sa-:sa-:sa-:sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂽",
	"Code point": "U+120BD",
	"Transliteration": "GA2×ASZ",
	"Borger": "389",
	"PaleoCode": "b;b';sa-;sa-::sb-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃢",
	"Code point": "U+120E2",
	"Transliteration": "SILA4 (GA2×PA)",
	"Borger": "408",
	"PaleoCode": "b;b';sa-;sa-:sb:sb-:sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁕",
	"Code point": "U+12055",
	"Transliteration": "DA",
	"Borger": "561",
	"PaleoCode": "B:sb:sb:sb:sb:sb:b--:a-:::sb-:::w-A",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁷",
	"Code point": "U+12077",
	"Transliteration": "DIN",
	"Borger": "119",
	"PaleoCode": "W:::W'-c;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀿",
	"Code point": "U+1203F",
	"Transliteration": "ASZGAB",
	"Borger": "173",
	"PaleoCode": ";B'a-:::sa-:::csa-:::sa-:::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃼",
	"Code point": "U+120FC",
	"Transliteration": "GAR3",
	"Borger": "543",
	"PaleoCode": "b:b:b:b_Wc;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃿",
	"Code point": "U+120FF",
	"Transliteration": "GESZTIN x KUR",
	"Borger": "213",
	"PaleoCode": "b:::b'::sa-::sa-W:::W-c;d':w::w-::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂂",
	"Code point": "U+12082",
	"Transliteration": "DUGUD",
	"Borger": "704",
	"PaleoCode": "W-:b:b:b:b_b:b:b:b_::/b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂅",
	"Code point": "U+12085",
	"Transliteration": "DUN3",
	"Borger": "836",
	"PaleoCode": "B;b'a--a::b_sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂢",
	"Code point": "U+120A2",
	"Transliteration": "EZEN x A",
	"Borger": "288",
	"PaleoCode": ":sa-:sb::sb-ab;b-:sa-:sa:sa-a-:sb::sb-:sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅅",
	"Code point": "U+12145",
	"Transliteration": "IG",
	"Borger": "136",
	"PaleoCode": ";B-a-b:b:b:b-a-a_:::w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅂",
	"Code point": "U+12142",
	"Transliteration": "IDIM",
	"Borger": "",
	"PaleoCode": "!b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇺",
	"Code point": "U+121FA",
	"Transliteration": "LISZ",
	"Borger": "591",
	"PaleoCode": "sc--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇻",
	"Code point": "U+121FB",
	"Transliteration": "LU",
	"Borger": "812",
	"PaleoCode": ":a-b;b-:::sb::-::sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈮",
	"Code point": "U+1222E",
	"Transliteration": "MUG",
	"Borger": "012",
	"PaleoCode": "b_ac;d-sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄈",
	"Code point": "U+12108",
	"Transliteration": "GIR2",
	"Borger": "006",
	"PaleoCode": ":B-::cd_c;dsa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈧",
	"Code point": "U+12227",
	"Transliteration": "MASZ2",
	"Borger": "130",
	"PaleoCode": ":b-a_;c'd_c;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍣",
	"Code point": "U+12363",
	"Transliteration": "ZI",
	"Borger": "140",
	"PaleoCode": ":B-a-a-W:W-w:w-w:w-w:w-W:W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊑",
	"Code point": "U+12291",
	"Transliteration": "RI",
	"Borger": "142",
	"PaleoCode": ":b'a-a-::w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅔",
	"Code point": "U+12154",
	"Transliteration": "IN",
	"Borger": "261",
	"PaleoCode": "w:w:w-w:w:w-w:w:w-c;dsa-;sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆒",
	"Code point": "U+12192",
	"Transliteration": "KAD4",
	"Borger": "568",
	"PaleoCode": "b:b:b:b_a::cd-a;b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆸",
	"Code point": "U+121B8",
	"Transliteration": "LAGAB",
	"Borger": "755",
	"PaleoCode": "a-b;b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆹",
	"Code point": "U+121B9",
	"Transliteration": "LAGAB x A",
	"Borger": "795",
	"PaleoCode": "a-b;b-:sa-:sa:sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇥",
	"Code point": "U+121E5",
	"Transliteration": "LAGAB x U",
	"Borger": "786",
	"PaleoCode": "a-b;b'::w_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇧",
	"Code point": "U+121E7",
	"Transliteration": "LAGAB x U + U + U",
	"Borger": "788",
	"PaleoCode": "a-b;b'::w-::w-::w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈖",
	"Code point": "U+12216",
	"Transliteration": "LU3",
	"Borger": "555",
	"PaleoCode": ":sb:sb:sb-a-b;b_a:sb:sb:sb",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆯",
	"Code point": "U+121AF",
	"Transliteration": "KU7",
	"Borger": "171",
	"PaleoCode": "b:::b_d;c_a::a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄘",
	"Code point": "U+12118",
	"Transliteration": "GU2",
	"Borger": "176",
	"PaleoCode": "b:::b-::sa--d;c_::a'c;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "TIK",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋛",
	"Code point": "U+122DB",
	"Transliteration": "SI",
	"Borger": "181",
	"PaleoCode": "B-;b'::sa_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋜",
	"Code point": "U+122DC",
	"Transliteration": "SU4",
	"Borger": "182",
	"PaleoCode": "B-;b'::sa--:sb:sb:sb-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "SI-gunu",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊕",
	"Code point": "U+12295",
	"Transliteration": "SAG",
	"Borger": "184",
	"PaleoCode": "d;c-::a_a:b::b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌉",
	"Code point": "U+12309",
	"Transliteration": "TUR",
	"Borger": "255",
	"PaleoCode": "a#:sc::scsd::sd--#:b:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "DUMU",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊐",
	"Code point": "U+12290",
	"Transliteration": "RAB",
	"Borger": "262",
	"PaleoCode": "::b:b-sb:sb:sb_/b::/b-/sb::sa-/sb",
	"SVG": "",
	"Gottstein": "",
	"Comment": "RAB",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌫",
	"Code point": "U+1232B",
	"Transliteration": "UR2",
	"Borger": "341",
	"PaleoCode": "sa-b::b_;c::c_;b:::b_;a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁉",
	"Code point": "U+12049",
	"Transliteration": "BI",
	"Borger": "358",
	"PaleoCode": "b;bsa-;sa_c;ad-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑊",
	"Code point": "U+1244A",
	"Transliteration": "TAB variant old",
	"Borger": "593",
	"PaleoCode": ":::sc-'::sc",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑢",
	"Code point": "U+12462",
	"Transliteration": "Number 1/4(Kültepe)",
	"Borger": "594",
	"PaleoCode": ":::sc-'::sc-::b-:b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌌",
	"Code point": "U+1230C",
	"Transliteration": "UL",
	"Borger": "698",
	"PaleoCode": "W_b::b_ac;d",
	"SVG": "",
	"Gottstein": "",
	"Comment": "DU7",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒎙",
	"Code point": "U+12399",
	"Transliteration": "MAN",
	"Borger": "708",
	"PaleoCode": "W-W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "2xU",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊔",
	"Code point": "U+12294",
	"Transliteration": "KISZI4",
	"Borger": "743",
	"PaleoCode": "d;c_a-:b::b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍮",
	"Code point": "U+1236E",
	"Transliteration": "ZUM",
	"Borger": "884",
	"PaleoCode": "Ac::b::d_d:d;c:c",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋼",
	"Code point": "U+122FC",
	"Transliteration": "TE",
	"Borger": "589",
	"PaleoCode": "d;c_ac;d_A",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌁",
	"Code point": "U+12301",
	"Transliteration": "TIR",
	"Borger": "587",
	"PaleoCode": "W::W-:w:w-:w:w-:w:w-W::W--B:::B-sa::sa-sa::sa-sa::sa-sa::sa-a:::a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌆",
	"Code point": "U+12306",
	"Transliteration": "TUG2",
	"Borger": "809",
	"PaleoCode": "ab;b-::sb:sb--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌇",
	"Code point": "U+12307",
	"Transliteration": "TUK",
	"Borger": "827",
	"PaleoCode": "a:::d-a-:sc",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌜",
	"Code point": "U+1231C",
	"Transliteration": "UDUG",
	"Borger": "833",
	"PaleoCode": ";w-a:::w-'a-a-:b::b-w--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌨",
	"Code point": "U+12328",
	"Transliteration": "UR",
	"Borger": "828",
	"PaleoCode": ";B'a-sa::b_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌪",
	"Code point": "U+1232A",
	"Transliteration": "UR szeszig",
	"Borger": "829",
	"PaleoCode": ";B'a-sa::b':w;w-:w;w--a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍇",
	"Code point": "U+12347",
	"Transliteration": "URU x MIN",
	"Borger": "080",
	"PaleoCode": "::B::B-a\"b-:sa-:sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍨",
	"Code point": "U+12368",
	"Transliteration": "ZIG",
	"Borger": "336",
	"PaleoCode": "sb:w:sb_b:::b':W-:W-:W",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍒",
	"Code point": "U+12352",
	"Transliteration": "USZ x A",
	"Borger": "384",
	"PaleoCode": "B;b';sa-;sa-:sa-:sa:sa';w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉆",
	"Code point": "U+12246",
	"Transliteration": "NAM",
	"Borger": "134",
	"PaleoCode": "::B-a;w-a;w-:::w-a-w::w::w-w::w::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌡",
	"Code point": "U+12321",
	"Transliteration": "UM x U",
	"Borger": "239",
	"PaleoCode": ":sb:sb-a-B;B':sa-:sa-:sa-:sa-::w-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋫",
	"Code point": "U+122EB",
	"Transliteration": "TA",
	"Borger": "248",
	"PaleoCode": "b;b_ac;d_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈗",
	"Code point": "U+12217",
	"Transliteration": "LUGAL",
	"Borger": "266",
	"PaleoCode": "b:b:b:b_a::b_a;B'::c::sc'-:C:::sa-;sa-;sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄠",
	"Code point": "U+12120",
	"Transliteration": "GUD x KUR",
	"Borger": "309",
	"PaleoCode": "b;b_ac;d':w:w-:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉈",
	"Code point": "U+12248",
	"Transliteration": "NE",
	"Borger": "313",
	"PaleoCode": "b::b'::w-:w-w::W--sb::sb-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {}, {
	"Sign": "𒀉",
	"Code point": "U+12009",
	"Transliteration": "A2",
	"Borger": "560",
	"PaleoCode": "B:sb:sb:sb:sb:sb:b--A-:w:w:/b-:w:w-:w:w-:::w'A",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀜",
	"Code point": "U+1201C",
	"Transliteration": "AD",
	"Borger": "258",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀠",
	"Code point": "U+12020",
	"Transliteration": "AL",
	"Borger": "474",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀩",
	"Code point": "U+12029",
	"Transliteration": "ALAN",
	"Borger": "573",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀭",
	"Code point": "U+1202D",
	"Transliteration": "AN",
	"Borger": "010",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀲",
	"Code point": "U+12032",
	"Transliteration": "ANSZE",
	"Borger": "353",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀳",
	"Code point": "U+12033",
	"Transliteration": "APIN",
	"Borger": "090",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀴",
	"Code point": "U+12034",
	"Transliteration": "ARAD",
	"Borger": "0018",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀶",
	"Code point": "U+12036",
	"Transliteration": "ARKAB",
	"Borger": "859v",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒀷",
	"Code point": "U+12037",
	"Transliteration": "ASAL2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁂",
	"Code point": "U+12042",
	"Transliteration": "BAG3",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁃",
	"Code point": "U+12043",
	"Transliteration": "BAHAR2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁆",
	"Code point": "U+12046",
	"Transliteration": "BALAG",
	"Borger": "565",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁈",
	"Code point": "U+12048",
	"Transliteration": "BARA2",
	"Borger": "554",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁯",
	"Code point": "U+1206F",
	"Transliteration": "DAR",
	"Borger": "183",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁰",
	"Code point": "U+12070",
	"Transliteration": "DARA3",
	"Borger": "166",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁱",
	"Code point": "U+12071",
	"Transliteration": "DARA4",
	"Borger": "817",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁶",
	"Code point": "U+12076",
	"Transliteration": "DIM2",
	"Borger": "686",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁺",
	"Code point": "U+1207A",
	"Transliteration": "DU",
	"Borger": "350",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒁾",
	"Code point": "U+1207E",
	"Transliteration": "DUB",
	"Borger": "242",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂀",
	"Code point": "U+12080",
	"Transliteration": "DUB2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂁",
	"Code point": "U+12081",
	"Transliteration": "DUG",
	"Borger": "499",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂄",
	"Code point": "U+12084",
	"Transliteration": "DUN",
	"Borger": "744",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂈",
	"Code point": "U+12088",
	"Transliteration": "DUN4",
	"Borger": "557",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂊",
	"Code point": "U+1208A",
	"Transliteration": "E",
	"Borger": "498",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂍",
	"Code point": "U+1208D",
	"Transliteration": "E2",
	"Borger": "495",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂔",
	"Code point": "U+12094",
	"Transliteration": "EDIN",
	"Borger": "300",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂕",
	"Code point": "U+12095",
	"Transliteration": "EGIR",
	"Borger": "356",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂗",
	"Code point": "U+12097",
	"Transliteration": "EN",
	"Borger": "164",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂞",
	"Code point": "U+1209E",
	"Transliteration": "EREN",
	"Borger": "818",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂟",
	"Code point": "U+1209F",
	"Transliteration": "ERIN2",
	"Borger": "612;613",
	"PaleoCode": "sc-::,sf::sc:sf",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒂵",
	"Code point": "U+120B5",
	"Transliteration": "GA",
	"Borger": "491",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃶",
	"Code point": "U+120F6",
	"Transliteration": "GAN",
	"Borger": "253",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒃽",
	"Code point": "U+120FD",
	"Transliteration": "GASZAN",
	"Borger": "562; 563",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍻",
	"Code point": "U+1237B",
	"Transliteration": "GE22",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄀",
	"Code point": "U+12100",
	"Transliteration": "GI",
	"Borger": "141",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄄",
	"Code point": "U+12104",
	"Transliteration": "GI4",
	"Borger": "507",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄇",
	"Code point": "U+12107",
	"Transliteration": "GIDIM",
	"Borger": "830",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍼",
	"Code point": "U+1237C",
	"Transliteration": "GIG",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄊",
	"Code point": "U+1210A",
	"Transliteration": "GIR3",
	"Borger": "701",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄖",
	"Code point": "U+12116",
	"Transliteration": "GU",
	"Borger": "891",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄢",
	"Code point": "U+12122",
	"Transliteration": "GUL",
	"Borger": "682",
	"PaleoCode": "::w_:b::b-_ab;b--::w;-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄣",
	"Code point": "U+12123",
	"Transliteration": "GUM",
	"Borger": "339",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄦",
	"Code point": "U+12126",
	"Transliteration": "GUR7",
	"Borger": "819",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄭",
	"Code point": "U+1212D",
	"Transliteration": "HI",
	"Borger": "631",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒄸",
	"Code point": "U+12138",
	"Transliteration": "HUB2",
	"Borger": "149",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍽",
	"Code point": "U+1237D",
	"Transliteration": "HUSZ",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅋",
	"Code point": "U+1214B",
	"Transliteration": "IL",
	"Borger": "348",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅍",
	"Code point": "U+1214D",
	"Transliteration": "IL2",
	"Borger": "493",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅎",
	"Code point": "U+1214E",
	"Transliteration": "IM",
	"Borger": "641",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅓",
	"Code point": "U+12153",
	"Transliteration": "IMIN",
	"Borger": "863",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅖",
	"Code point": "U+12156",
	"Transliteration": "ISZ",
	"Borger": "357",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒅗",
	"Code point": "U+12157",
	"Transliteration": "KA",
	"Borger": "024",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆍",
	"Code point": "U+1218D",
	"Transliteration": "KA2",
	"Borger": "222",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆓",
	"Code point": "U+12193",
	"Transliteration": "KAD5",
	"Borger": "569",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆛",
	"Code point": "U+1219B",
	"Transliteration": "KAM4",
	"Borger": "097",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍯",
	"Code point": "U+1236F",
	"Transliteration": "KAP ELAMITE",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆟",
	"Code point": "U+1219F",
	"Transliteration": "KESZ2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆥",
	"Code point": "U+121A5",
	"Transliteration": "KIN",
	"Borger": "815",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆧",
	"Code point": "U+121A7",
	"Transliteration": "KISZ",
	"Borger": "678",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆨",
	"Code point": "U+121A8",
	"Transliteration": "KISIM5",
	"Borger": "687",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆪",
	"Code point": "U+121AA",
	"Transliteration": "KU",
	"Borger": "808",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆬",
	"Code point": "U+121AC",
	"Transliteration": "KU3",
	"Borger": "745",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆭",
	"Code point": "U+121AD",
	"Transliteration": "KU4",
	"Borger": "087",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆮",
	"Code point": "U+121AE",
	"Transliteration": "KU4 variant form",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆲",
	"Code point": "U+121B2",
	"Transliteration": "KUN",
	"Borger": "131",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆵",
	"Code point": "U+121B5",
	"Transliteration": "KUSZU2",
	"Borger": "896",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆶",
	"Code point": "U+121B6",
	"Transliteration": "KWU318",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒆷",
	"Code point": "U+121B7",
	"Transliteration": "LA",
	"Borger": "089",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇱",
	"Code point": "U+121F1",
	"Transliteration": "LAHSZU",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇴",
	"Code point": "U+121F4",
	"Transliteration": "LAM",
	"Borger": "693",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇷",
	"Code point": "U+121F7",
	"Transliteration": "LI",
	"Borger": "085",
	"PaleoCode": "W::W-::sw:sw-::sw:sw-::sw:sw-W::W-b:b:b:b_aC::D_a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇸",
	"Code point": "U+121F8",
	"Transliteration": "LIL",
	"Borger": "544",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒇽",
	"Code point": "U+121FD",
	"Transliteration": "LU2",
	"Borger": "514",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈜",
	"Code point": "U+1221C",
	"Transliteration": "LUL",
	"Borger": "570",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈤",
	"Code point": "U+12224",
	"Transliteration": "MAH",
	"Borger": "091",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈩",
	"Code point": "U+12229",
	"Transliteration": "MES",
	"Borger": "486",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈰",
	"Code point": "U+12230",
	"Transliteration": "MUNSUB",
	"Borger": "820",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈱",
	"Code point": "U+12231",
	"Transliteration": "MURGU2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈲",
	"Code point": "U+12232",
	"Transliteration": "MUSZ",
	"Borger": "585",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈹",
	"Code point": "U+12239",
	"Transliteration": "MUSZ3",
	"Borger": "153",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈾",
	"Code point": "U+1223E",
	"Transliteration": "NA",
	"Borger": "110",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒈿",
	"Code point": "U+1223F",
	"Transliteration": "NA2",
	"Borger": "689",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒎎",
	"Code point": "U+1238E",
	"Transliteration": "NA4",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉀",
	"Code point": "U+12240",
	"Transliteration": "NAGA",
	"Borger": "293",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "sex appeal",
	"Concept":"https://www.wikidata.org/wiki/Q7458551",
	"Location": ""
}, {
	"Sign": "𒉄",
	"Code point": "U+12244",
	"Transliteration": "NAGAR",
	"Borger": "893",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "carpenter",
	"Concept":"https://www.wikidata.org/wiki/Q154549",
	"Location": ""
}, {
	"Sign": "𒉇",
	"Code point": "U+12247",
	"Transliteration": "NAM2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "forethought",
	"Concept":"https://www.wikidata.org/wiki/Q309100",
	"Location": ""
}, {
	"Sign": "𒉎",
	"Code point": "U+1224E",
	"Transliteration": "NI2",
	"Borger": "641",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉏",
	"Code point": "U+1224F",
	"Transliteration": "NIM",
	"Borger": "690",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒎏",
	"Code point": "U+1238F",
	"Transliteration": "NIN",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒎐",
	"Code point": "U+12390",
	"Transliteration": "NIN9",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉠",
	"Code point": "U+12260",
	"Transliteration": "NISAG",
	"Borger": "545",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉢",
	"Code point": "U+12262",
	"Transliteration": "NU11",
	"Borger": "115",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "male",
	"Concept":"https://www.wikidata.org/wiki/Q6581097",
	"Location": ""
}, {
	"Sign": "𒉭",
	"Code point": "U+1226D",
	"Transliteration": "NUNUZ",
	"Borger": "614",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉻",
	"Code point": "U+1227B",
	"Transliteration": "PAD",
	"Borger": "746",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉾",
	"Code point": "U+1227E",
	"Transliteration": "PESZ2",
	"Borger": "741; 882",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒉿",
	"Code point": "U+1227F",
	"Transliteration": "PI",
	"Borger": "598",
	"PaleoCode": "W:::W-A-::b",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒎕",
	"Code point": "U+12395",
	"Transliteration": "PIR2",
	"Borger": "",
	"PaleoCode": "sc::sc-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊊",
	"Code point": "U+1228A",
	"Transliteration": "PIRIG",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "strength",
	"Concept":"https://www.wikidata.org/wiki/Q605035",
	"Location": ""
}, {
	"Sign": "𒊏",
	"Code point": "U+1228F",
	"Transliteration": "RA",
	"Borger": "511",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊒",
	"Code point": "U+12292",
	"Transliteration": "RU",
	"Borger": "111",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊓",
	"Code point": "U+12293",
	"Transliteration": "SA",
	"Borger": "172",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊫",
	"Code point": "U+122AB",
	"Transliteration": "SANGA2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "a priest",
	"Concept":"https://www.wikidata.org/wiki/Q42603",
	"Location": ""
}, {
	"Sign": "𒊮",
	"Code point": "U+122AE",
	"Transliteration": "SZA3",
	"Borger": "599",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊷",
	"Code point": "U+122B7",
	"Transliteration": "SZA6",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "wing",
	"Concept":"https://www.wikidata.org/wiki/Q161358",
	"Location": ""
}, {
	"Sign": "𒊹",
	"Code point": "U+122B9",
	"Transliteration": "SZAR2",
	"Borger": "632; 633",
	"PaleoCode": "x",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒊾",
	"Code point": "U+122BE",
	"Transliteration": "SZEG9",
	"Borger": "878",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "snow",
	"Concept":"https://www.wikidata.org/wiki/Q7561",
	"Location": ""
}, {
	"Sign": "𒊿",
	"Code point": "U+122BF",
	"Transliteration": "SZEN",
	"Borger": "017",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "axe",
	"Concept":"https://www.wikidata.org/wiki/Q39397",
	"Location": ""
}, {
	"Sign": "𒋀",
	"Code point": "U+122C0",
	"Transliteration": "SZESZ",
	"Borger": "535",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋁",
	"Code point": "U+122C1",
	"Transliteration": "SZESZ2",
	"Borger": "821",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋆",
	"Code point": "U+122C6",
	"Transliteration": "SZIM",
	"Borger": "362",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "exultation",
	"Concept":"",
	"Location": ""
}, {
	"Sign": "𒋒",
	"Code point": "U+122D2",
	"Transliteration": "SZINIG",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "tamarisk",
	"Concept":"https://www.wikidata.org/wiki/Q164163",
	"Location": ""
}, {
	"Sign": "𒋓",
	"Code point": "U+122D3",
	"Transliteration": "SZIR",
	"Borger": "115",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "testicles",
	"Concept":"https://www.wikidata.org/wiki/Q9384",
	"Location": ""
}, {
	"Sign": "𒋚",
	"Code point": "U+122DA",
	"Transliteration": "SZUBUR",
	"Borger": "0022",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋝",
	"Code point": "U+122DD",
	"Transliteration": "SIG",
	"Borger": "881",
	"PaleoCode": "sf-::sc--:sc::sf",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "drinking vessel",
	"Concept":"https://www.wikidata.org/wiki/Q2453629",
	"Location": ""
}, {
	"Sign": "𒋞",
	"Code point": "U+122DE",
	"Transliteration": "SIG4",
	"Borger": "905; 906",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋠",
	"Code point": "U+122E0",
	"Transliteration": "SIK2",
	"Borger": "816",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋢",
	"Code point": "U+122E2",
	"Transliteration": "SU",
	"Borger": "016",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋤",
	"Code point": "U+122E4",
	"Transliteration": "SUD",
	"Borger": "584",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋦",
	"Code point": "U+122E6",
	"Transliteration": "SUHUR",
	"Borger": "646",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋧",
	"Code point": "U+122E7",
	"Transliteration": "SUM",
	"Borger": "292",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋨",
	"Code point": "U+122E8",
	"Transliteration": "SUMASZ",
	"Borger": "323",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋩",
	"Code point": "U+122E9",
	"Transliteration": "SUR",
	"Borger": "151",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋪",
	"Code point": "U+122EA",
	"Transliteration": "SUR9",
	"Borger": "205",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋳",
	"Code point": "U+122F3",
	"Transliteration": "TAG",
	"Borger": "221",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒋺",
	"Code point": "U+122FA",
	"Transliteration": "TAK4",
	"Borger": "106",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "reed shelter",
	"Concept":"https://www.wikidata.org/wiki/Q7493941",
	"Location": ""
}, {
	"Sign": "𒎗",
	"Code point": "U+12397",
	"Transliteration": "TI2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌅",
	"Code point": "U+12305",
	"Transliteration": "TU",
	"Borger": "086",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌈",
	"Code point": "U+12308",
	"Transliteration": "TUM",
	"Borger": "354",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌓",
	"Code point": "U+12313",
	"Transliteration": "UD",
	"Borger": "596",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌢",
	"Code point": "U+12322",
	"Transliteration": "UMBIN",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌣",
	"Code point": "U+12323",
	"Transliteration": "UMUM",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "head smith",
	"Concept":"https://www.wikidata.org/wiki/Q1639825",
	"Location": ""
}, {
	"Sign": "𒌦",
	"Code point": "U+12326",
	"Transliteration": "UN",
	"Borger": "501",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "land of Sumer",
	"Concept":"https://www.wikidata.org/wiki/Q35355",
	"Location": ""
}, {
	"Sign": "𒌴",
	"Code point": "U+12334",
	"Transliteration": "UR4",
	"Borger": "835",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒌵",
	"Code point": "U+12335",
	"Transliteration": "URI",
	"Borger": "574",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "vessel",
	"Concept":"https://www.wikidata.org/wiki/Q987767",
	"Location": ""
}, {
	"Sign": "𒌶",
	"Code point": "U+12336",
	"Transliteration": "URI3",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍗",
	"Code point": "U+12357",
	"Transliteration": "USZ2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍖",
	"Code point": "U+12356",
	"Transliteration": "USZX",
	"Borger": "583",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍘",
	"Code point": "U+12358",
	"Transliteration": "USZUMX",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍙",
	"Code point": "U+12359",
	"Transliteration": "UTUKI",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍚",
	"Code point": "U+1235A",
	"Transliteration": "UZ3",
	"Borger": "203",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "female goat",
	"Concept":"https://www.wikidata.org/wiki/Q172923",
	"Location": ""
}, {
	"Sign": "𒍜",
	"Code point": "U+1235C",
	"Transliteration": "UZU",
	"Borger": "311",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "flesh",
	"Concept":"https://www.wikidata.org/wiki/Q13119823",
	"Location": ""
}, {
	"Sign": "𒍠",
	"Code point": "U+12360",
	"Transliteration": "ZAG",
	"Borger": "540",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍡",
	"Code point": "U+12361",
	"Transliteration": "ZAMX",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍢",
	"Code point": "U+12362",
	"Transliteration": "ZE2",
	"Borger": "259",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "gall bladder",
	"Concept":"https://www.wikidata.org/wiki/Q64386",
	"Location": ""
}, {
	"Sign": "𒍥",
	"Code point": "U+12365",
	"Transliteration": "ZI3",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍩",
	"Code point": "U+12369",
	"Transliteration": "ZIZ2",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍪",
	"Code point": "U+1236A",
	"Transliteration": "ZU",
	"Borger": "015",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒍫",
	"Code point": "U+1236B",
	"Transliteration": "ZU5",
	"Borger": "",
	"PaleoCode": "XXX",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "doctor",
	"Concept":"https://www.wikidata.org/wiki/Q39631",
	"Location": ""
}, {
	"Sign": "𒐈",
	"Code point": "U+12408",
	"Transliteration": "3(disz)",
	"Borger": "834",
	"PaleoCode": "a-a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "3",
	"Concept":"https://www.wikidata.org/wiki/Q201",
	"Location": ""
}, {
	"Sign": "𒐉",
	"Code point": "U+12409",
	"Transliteration": "4(disz)",
	"Borger": "851; 852; 853",
	"PaleoCode": "sa::sa-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "4",
	"Concept":"https://www.wikidata.org/wiki/Q202",
	"Location": ""
}, {
	"Sign": "𒐋",
	"Code point": "U+1240B",
	"Transliteration": "6(disz)",
	"Borger": "862",
	"PaleoCode": "sa::sa-sa::sa-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "6",
	"Concept":"https://www.wikidata.org/wiki/Q23488",
	"Location": ""
}, {
	"Sign": "𒐍",
	"Code point": "U+1240D",
	"Transliteration": "8(disz)",
	"Borger": "862",
	"PaleoCode": "sa::sa-sa::sa-sa::sa-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "8",
	"Concept":"https://www.wikidata.org/wiki/Q23355",
	"Location": ""
}, {
	"Sign": "𒐍",
	"Code point": "U+1240E",
	"Transliteration": "9(disz)",
	"Borger": "862",
	"PaleoCode": "sa::sa-sa::sa-sa::sa-sa::sa-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "9",
	"Concept":"https://www.wikidata.org/wiki/Q19108",
	"Location": ""
}, {
	"Sign": "𒐕",
	"Code point": "U+12415",
	"Transliteration": "1(gesz2)",
	"Borger": "",
	"PaleoCode": "a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "40",
	"Concept":"https://www.wikidata.org/wiki/Q42317",
	"Location": ""
}, {
	"Sign": "𒐖",
	"Code point": "U+12416",
	"Transliteration": "2(gesz2)",
	"Borger": "",
	"PaleoCode": "a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐗",
	"Code point": "U+12417",
	"Transliteration": "3(gesz2)",
	"Borger": "",
	"PaleoCode": "a-a-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐘",
	"Code point": "U+12418",
	"Transliteration": "4(gesz2)",
	"Borger": "",
	"PaleoCode": "sa::sa-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐙",
	"Code point": "U+12419",
	"Transliteration": "5(gesz2)",
	"Borger": "",
	"PaleoCode": "sa::sa-sa::sa-sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐚",
	"Code point": "U+1241A",
	"Transliteration": "6(gesz2)",
	"Borger": "",
	"PaleoCode": "sa::sa-sa::sa-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐛",
	"Code point": "U+1241B",
	"Transliteration": "7(gesz2)",
	"Borger": "",
	"PaleoCode": "sa::sa-sa::sa-sa::sa-sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐜",
	"Code point": "U+1241C",
	"Transliteration": "8(gesz2)",
	"Borger": "",
	"PaleoCode": "sa::sa-sa::sa-sa::sa-sa::sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐝",
	"Code point": "U+1241D",
	"Transliteration": "9(gesz2)",
	"Borger": "",
	"PaleoCode": "sa::sa-sa::sa-sa::sa-sa::sa-sa",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
},{
	"Sign": "𒐐",
	"Code point": "U+12410",
	"Transliteration": "5(u)",
	"Borger": "714",
	"PaleoCode": "w:w-w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "50",
	"Concept":"https://www.wikidata.org/wiki/Q712519",
	"Location": ""
}, {
	"Sign": "𒐑",
	"Code point": "U+12411",
	"Transliteration": "6(u)",
	"Borger": "715",
	"PaleoCode": "w:w-w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Meaning": "60",
	"Concept":"https://www.wikidata.org/wiki/Q79998",
	"Location": ""
}, {
	"Sign": "𒐒",
	"Code point": "U+12412",
	"Transliteration": "7(u)",
	"Borger": "716",
	"PaleoCode": "w:w-w:w-w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}
, {
	"Sign": "𒐓",
	"Code point": "U+12413",
	"Transliteration": "8(u)",
	"Borger": "717",
	"PaleoCode": "w:w-w:w-w:w-w:w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}
, {
	"Sign": "𒐔",
	"Code point": "U+12414",
	"Transliteration": "9(u)",
	"Borger": "718",
	"PaleoCode": "w:w-w:w-w:w-w:w-w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑏",
	"Code point": "U+1244F",
	"Transliteration": "1(ban2)",
	"Borger": "",
	"PaleoCode": ":/b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑐",
	"Code point": "U+12450",
	"Transliteration": "2(ban2)",
	"Borger": "",
	"PaleoCode": ":b/:b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒑑",
	"Code point": "U+12451",
	"Transliteration": "3(ban2)",
	"Borger": "",
	"PaleoCode": "b:/b:/b-a",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐞",
	"Code point": "U+1241E",
	"Transliteration": "geszu",
	"Borger": "",
	"PaleoCode": "a::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐟",
	"Code point": "U+1241F",
	"Transliteration": "2(geszu)",
	"Borger": "",
	"PaleoCode": "a::w-a::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐠",
	"Code point": "U+12420",
	"Transliteration": "3(geszu)",
	"Borger": "",
	"PaleoCode": "a::w-a::w-a::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐡",
	"Code point": "U+12421",
	"Transliteration": "4(geszu)",
	"Borger": "",
	"PaleoCode": "a::w:a::w-a::w:a::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}, {
	"Sign": "𒐢",
	"Code point": "U+12422",
	"Transliteration": "5(geszu)",
	"Borger": "",
	"PaleoCode": "a::w:a::w-a::w:a::w-a::w",
	"SVG": "",
	"Gottstein": "",
	"Comment": "",
	"Source": "",
	"Epoch": "",
	"Location": ""
}

]
